Repository mspnp/aks-baseline, pull requests merged in 2022-05, with the labels that each got.

#306 Fixup a situation where Azure RBAC role ID was mis-identified
  cluster-stamp.bicep
Labels: bug

#311 RBAC fix, doc consistency, minor improvements.
  01-prerequisites.md
  03-aad.md
  04-networking.md
  06-aks-cluster.md
  09-secret-management-and-ingress-controller.md
  10-workload.md
  11-validation.md
  CONTRIBUTING.md
  cluster-stamp.bicep
  inner-loop-scripts/shell/1-cluster-stamp.sh
  saveenv.sh
Labels: documentation, enhancement

#315 Fix: Peering name length for long region names.
  networking/spoke-BU0001A0008.bicep
Labels: bug

#317 Azure Policy Refresh
  acr-stamp.bicep
  cluster-stamp.bicep
Labels: enhancement

#324 Move legacy saved queries to a dedicated query pack
  11-validation.md
  cluster-stamp.bicep
Labels: enhancement
